const audio = document.getElementById('main-audio');
const playPauseBtn = document.getElementById('play-pause-btn');
const playIcon = document.getElementById('play-icon');
const progressBar = document.getElementById('progress-bar');
const timeCurrent = document.getElementById('time-current');
const timeTotal = document.getElementById('time-total');
const songTitle = document.getElementById('song-title');
const artistName = document.getElementById('artist-name');
const volumeBtn = document.getElementById('volume-btn');
const volumePopover = document.getElementById('volume-popover');
const volumeBar = document.getElementById('volume-bar');
const musicPlayer = document.getElementById('music-player');
const randomBtn = document.getElementById('random-btn');
const diceIcon = document.getElementById('dice-icon');
const container = document.getElementById('song-list-container');

/**
 * AUTO-IMPORT CONFIGURATION
  * This uses the GitHub API to fetch all files in your folder automatically.
   */
   const USER = "raeist-user";
   const REPO = "Webt";
   const FOLDER = "music";
   const API_URL = `https://api.github.com/repos/${USER}/${REPO}/contents/${FOLDER}`;
   const RAW_BASE = `https://raw.githubusercontent.com/${USER}/${REPO}/main/${FOLDER}/`;

   let songs = [];

   // 1. DYNAMIC IMPORT FUNCTION
   async function importMusicFromGithub() {
       try {
               const response = await fetch(API_URL);
                       const files = await response.json();
                               
                                       // Filter only audio files and build the playlist
                                               songs = files
                                                           .filter(file => file.name.match(/\.(mp3|wav|irc|ogg)$/i))
                                                                       .map(file => {
                                                                                       const cleanName = file.name.replace(/\.[^/.]+$/, "").replace(/[-_]/g, ' ');
                                                                                                       return {
                                                                                                                           t: cleanName,
                                                                                                                                               a: "Library Track",
                                                                                                                                                                   file: file.name
                                                                                                                                                                                   };
                                                                                                                                                                                               });

                                                                                                                                                                                                       renderLibrary();
                                                                                                                                                                                                               console.log(`Successfully imported ${songs.length} songs from GitHub.`);
                                                                                                                                                                                                                   } catch (error) {
                                                                                                                                                                                                                           console.error("Failed to auto-import music:", error);
                                                                                                                                                                                                                                   document.getElementById('status-label').innerText = "Import Error";
                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                       function formatTime(secs) {
                                                                                                                                                                                                                                           if (isNaN(secs)) return "0:00";
                                                                                                                                                                                                                                               const min = Math.floor(secs / 60);
                                                                                                                                                                                                                                                   const sec = Math.floor(secs % 60);
                                                                                                                                                                                                                                                       return `${min}:${sec < 10 ? '0' : ''}${sec}`;
                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                       function loadSong(index) {
                                                                                                                                                                                                                                                           if (!songs[index]) return;
                                                                                                                                                                                                                                                               const s = songs[index];
                                                                                                                                                                                                                                                                   songTitle.innerText = s.t;
                                                                                                                                                                                                                                                                       artistName.innerText = s.a;
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               audio.src = RAW_BASE + s.file;
                                                                                                                                                                                                                                                                                   audio.play().catch(e => console.error("Playback error", e));
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                           playIcon.className = "fas fa-pause";
                                                                                                                                                                                                                                                                                               musicPlayer.classList.add('is-expanded');
                                                                                                                                                                                                                                                                                                   document.getElementById('status-label').innerText = "Now Playing";
                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                   function renderLibrary() {
                                                                                                                                                                                                                                                                                                       container.innerHTML = ""; // Clear existing
                                                                                                                                                                                                                                                                                                           songs.forEach((s, i) => {
                                                                                                                                                                                                                                                                                                                   const div = document.createElement('div');
                                                                                                                                                                                                                                                                                                                           div.className = "song-item";
                                                                                                                                                                                                                                                                                                                                   div.innerHTML = `
                                                                                                                                                                                                                                                                                                                                               <div class="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                               <div class="w-10 h-10 bg-black/5 rounded-lg flex items-center justify-center text-xs font-bold">${i+1}</div>
                                                                                                                                                                                                                                                                                                                                                                               <div>
                                                                                                                                                                                                                                                                                                                                                                                                   <div class="font-bold text-[0.9rem]">${s.t}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="text-[0.7rem] opacity-40 uppercase tracking-tight">${s.a}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                               <i class="fas fa-play text-xs opacity-10"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               div.onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           loadSong(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       document.getElementById('playlist-overlay').classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       container.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // UI HANDLERS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           document.getElementById('open-library').onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               document.getElementById('playlist-overlay').classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               document.getElementById('toggle-menu').onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   musicPlayer.classList.toggle('is-expanded');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   randomBtn.onclick = (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           diceIcon.classList.remove('dice-roll');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               void diceIcon.offsetWidth; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   diceIcon.classList.add('dice-roll');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (songs.length > 0) loadSong(Math.floor(Math.random() * songs.length));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       playPauseBtn.onclick = (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (songs.length === 0) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!audio.src) { loadSong(0); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (audio.paused) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               audio.play();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       playIcon.className = "fas fa-pause";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   audio.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           playIcon.className = "fas fa-play ml-1";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               audio.ontimeupdate = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const per = (audio.currentTime / audio.duration) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       progressBar.value = per || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           timeCurrent.innerText = formatTime(audio.currentTime);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (!isNaN(audio.duration)) timeTotal.innerText = formatTime(audio.duration);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               progressBar.oninput = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const time = (progressBar.value / 100) * audio.duration;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       audio.currentTime = time;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       volumeBtn.onclick = (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               volumePopover.classList.toggle('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               volumeBar.oninput = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   audio.volume = volumeBar.value / 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   document.getElementById('close-overlay').onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       document.getElementById('playlist-overlay').classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       document.addEventListener('click', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!volumeBtn.contains(e.target) && !volumePopover.contains(e.target)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   volumePopover.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // START THE AUTO-IMPORT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       importMusicFromGithub();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
/*
t audio = document.getElementById('main-audio');
const playPauseBtn = document.getElementById('play-pause-btn');
const playIcon = document.getElementById('play-icon');
const progressBar = document.getElementById('progress-bar');
const timeCurrent = document.getElementById('time-current');
const timeTotal = document.getElementById('time-total');
const songTitle = document.getElementById('song-title');
const artistName = document.getElementById('artist-name');
const volumeBtn = document.getElementById('volume-btn');
const volumePopover = document.getElementById('volume-popover');
const volumeBar = document.getElementById('volume-bar');
const musicPlayer = document.getElementById('music-player');
const randomBtn = document.getElementById('random-btn');
const diceIcon = document.getElementById('dice-icon');

/**
 * PATH CONFIGURATION
  * Folder: music/
   * GitHub: raeist-user/Webt
    
    const GITHUB_RAW_BASE = "https://raw.githubusercontent.com/raeist-user/Webt/main/music/";

    // 1. ADD YOUR FILENAMES HERE (Exact names from your GitHub 'music' folder)
    const musicFiles = [
        "Tum-Se-Hi.mp3",
            "Kun-Faya-Kun.mp3",
                "Agar-Tum-Saath-Ho.mp3",
                    "Dil-Diyan-Gallan.mp3"
                    ];

                    // 2. AUTOMATIC TITLE GENERATION
                    const songs = musicFiles.map(file => {
                        // Remove extension and replace dashes/underscores with spaces
                            const cleanName = file.replace(/\.[^/.]+$/, "").replace(/[-_]/g, ' ');
                                return {
                                        t: cleanName,
                                                a: "Library Track",
                                                        file: file
                                                            };
                                                            });

                                                            function formatTime(secs) {
                                                                if (isNaN(secs)) return "0:00";
                                                                    const min = Math.floor(secs / 60);
                                                                        const sec = Math.floor(secs % 60);
                                                                            return `${min}:${sec < 10 ? '0' : ''}${sec}`;
                                                                            }

                                                                            function loadSong(index) {
                                                                                const s = songs[index];
                                                                                    songTitle.innerText = s.t;
                                                                                        artistName.innerText = s.a;
                                                                                            
                                                                                                // Construct the absolute Raw GitHub URL
                                                                                                    audio.src = https://raw.githubusercontent.com/raeist-user/Webt/main/music/ + s.file;
*/                                                                                                        
                                                                                                         /*   audio.play().catch(e => {
                                                                                                                    console.error("Link Error: Is '" + s.file + "' in the 'music' folder on GitHub?");
                                                                                                                        });
                                                                                                                            
                                                                                                                                playIcon.className = "fas fa-pause";
                                                                                                                                    musicPlayer.classList.add('is-expanded');
                                                                                                                                        document.getElementById('status-label').innerText = "Now Playing";
                                                                                                                                        }

                                                                                                                                        // UI HANDLERS
                                                                                                                                        document.getElementById('open-library').onclick = () => {
                                                                                                                                            document.getElementById('playlist-overlay').classList.add('active');
                                                                                                                                            };

                                                                                                                                            document.getElementById('toggle-menu').onclick = () => {
                                                                                                                                                musicPlayer.classList.toggle('is-expanded');
                                                                                                                                                };

                                                                                                                                                randomBtn.onclick = (e) => {
                                                                                                                                                    e.stopPropagation();
                                                                                                                                                        diceIcon.classList.remove('dice-roll');
                                                                                                                                                            void diceIcon.offsetWidth; 
                                                                                                                                                                diceIcon.classList.add('dice-roll');
                                                                                                                                                                    const randomIndex = Math.floor(Math.random() * songs.length);
                                                                                                                                                                        loadSong(randomIndex);
                                                                                                                                                                        };

                                                                                                                                                                        playPauseBtn.onclick = (e) => {
                                                                                                                                                                            e.stopPropagation();
                                                                                                                                                                                if (!audio.src) { loadSong(0); return; }
                                                                                                                                                                                    if (audio.paused) {
                                                                                                                                                                                            audio.play();
                                                                                                                                                                                                    playIcon.className = "fas fa-pause";
                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                audio.pause();
                                                                                                                                                                                                                        playIcon.className = "fas fa-play ml-1";
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                            audio.ontimeupdate = () => {
                                                                                                                                                                                                                                const per = (audio.currentTime / audio.duration) * 100;
                                                                                                                                                                                                                                    progressBar.value = per || 0;
                                                                                                                                                                                                                                        timeCurrent.innerText = formatTime(audio.currentTime);
                                                                                                                                                                                                                                            if (!isNaN(audio.duration)) timeTotal.innerText = formatTime(audio.duration);
                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                            progressBar.oninput = () => {
                                                                                                                                                                                                                                                const time = (progressBar.value / 100) * audio.duration;
                                                                                                                                                                                                                                                    audio.currentTime = time;
                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                    volumeBtn.onclick = (e) => {
                                                                                                                                                                                                                                                        e.stopPropagation();
                                                                                                                                                                                                                                                            volumePopover.classList.toggle('active');
                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                            volumeBar.oninput = () => {
                                                                                                                                                                                                                                                                audio.volume = volumeBar.value / 100;
                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                document.getElementById('close-overlay').onclick = () => {
                                                                                                                                                                                                                                                                    document.getElementById('playlist-overlay').classList.remove('active');
                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                    // INITIALIZE LIST
                                                                                                                                                                                                                                                                    const container = document.getElementById('song-list-container');
                                                                                                                                                                                                                                                                    songs.forEach((s, i) => {
                                                                                                                                                                                                                                                                        const div = document.createElement('div');
                                                                                                                                                                                                                                                                            div.className = "song-item";
                                                                                                                                                                                                                                                                                div.innerHTML = `
                                                                                                                                                                                                                                                                                        <div class="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                    <div class="w-10 h-10 bg-black/5 rounded-lg flex items-center justify-center text-xs font-bold">${i+1}</div>
                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                <div class="font-bold text-[0.9rem]">${s.t}</div>
                                                                                                                                                                                                                                                                                                                                                <div class="text-[0.7rem] opacity-40 uppercase tracking-tight">${s.a}</div>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                            <i class="fas fa-play text-xs opacity-10"></i>
                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                    div.onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                            loadSong(i);
                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('playlist-overlay').classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                            container.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                            document.addEventListener('click', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                if (!volumeBtn.contains(e.target) && !volumePopover.contains(e.target)) {
                                                                                                                                                                                                                                                                                                                                                                                                                        volumePopover.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    */